### ISSUE TITLE
2021.1.0b0 error

### ISSUE THREAD

**Issue by DavidFW1960** [exxamalte/home-assistant-custom-components-nsw-rural-fire-service-fire-danger#18]
I know you will be THRILLED to hear this but the latest beta has broken this again. Seems the same error as previously - I wonder if they reverted a PR?

```
2020-12-31 09:04:59 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Greater Sydney Region for nsw_rural_fire_service_fire_danger
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/nsw_rural_fire_service_fire_danger/__init__.py", line 82, in async_setup_entry
manager = NswRfsFireDangerFeedEntityManager(hass, config_entry)
File "/config/custom_components/nsw_rural_fire_service_fire_danger/__init__.py", line 118, in __init__
self._rest = RestData(
TypeError: __init__() missing 1 required positional argument: 'verify_ssl'
```

**Comment by exxamalte** [comment]
Quick analysis indicates that this issue was introduced with https://github.com/home-assistant/core/pull/43877 where a new parameter was addded to `RestData`'s constructor.
I'll have a look how to best fix this custom component...

**Comment by exxamalte** [comment]
Fixed in v0.6

**Comment by DavidFW1960** [comment]
Thanks mate...
